options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/articulate-area-464808-q4/secrets/slack-webhook-url/versions/latest
      env: SLACK_WEBHOOK_URL

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/articulate-area-464808-q4/slack-notify/sample-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/articulate-area-464808-q4/slack-notify/sample-app']

  - name: 'curlimages/curl'
    id: notify-success
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ *Build SUCCESS* for sample-app in project *articulate-area-464808-q4*."}' \
          "$SLACK_WEBHOOK_URL"

