steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sample-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sample-app']

  - name: 'curlimages/curl'
    id: notify-success
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ *Build SUCCESS* for sample-app in project *$PROJECT_ID*."}' \
          "$SLACK_WEBHOOK_URL"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/slack-webhook-url/versions/latest
      env: SLACK_WEBHOOK_URL

timeout: 900s

failure:
  steps:
    - name: 'curlimages/curl'
      id: notify-failure
      entrypoint: 'sh'
      args:
        - '-c'
        - |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"❌ *Build FAILED* for sample-app in project *$PROJECT_ID*."}' \
            "$SLACK_WEBHOOK_URL"
