options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/articulate-area-464808-q4/secrets/SLACK_WEBHOOK_URL/versions/latest
      env: SLACK_WEBHOOK_URL

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/articulate-area-464808-q4/slack-notify/sample-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/articulate-area-464808-q4/slack-notify/sample-app']

  - name: 'curlimages/curl'
    id: notify-success
    secretEnv: ['SLACK_WEBHOOK_URL']
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        curl -X POST -H "Content-Type: application/json" \
          -d "{
                \"color\": \"#36a64f\",
                \"title\": \"✅ New version deployed to BE environment\",
                \"text\": \"*Deployment Details*\n\n*Environment:* ${_ENV}\n*Project:* articulate-area-464808-q4\n*Service:* gitinfo-demo\n*Version:* ${SHORT_SHA}\"
          }" \
          "$$SLACK_WEBHOOK_URL"

              
  - name: 'curlimages/curl'
    id: notify-success
    secretEnv: ['SLACK_WEBHOOK_URL']
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        curl -X POST -H "Content-Type: application/json" \
          -d "{
                \"attachments\": [
                  {
                    \"color\": \"#36a64f\",
                    \"title\": \"✅ New version deployed to BE environment\",
                    \"text\": \"*Deployment Details:*\n\n*Environment:* *dev*\n*Project:* *articulate-area-464808-q4*\n*Service:* *gitinfo-demo*\n*Version:* *${SHORT_SHA}*\",
                    \"mrkdwn_in\": [\"text\", \"title\"]
                  }
                ]
              }" \
          \"$$SLACK_WEBHOOK_URL\"
