options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/articulate-area-464808-q4/secrets/SLACK_WEBHOOK_URL/versions/latest
      env: SLACK_WEBHOOK_URL

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/articulate-area-464808-q4/slack-notify/sample-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/articulate-area-464808-q4/slack-notify/sample-app']

  - name: 'curlimages/curl'
    id: notify-success
    secretEnv: ['SLACK_WEBHOOK_URL']
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        curl -X POST -H "Content-Type: application/json" \
        --data "{
          \"text\": \"✅ New version deployed to BE environment\n\n*Deployment Details*\nEnvironment: dev \nProject: articulate-area-464808-q4\nService: gitinfo-demo\nVersion: ${SHORT_SHA}\"
        }" \
        "$$SLACK_WEBHOOK_URL"
