substitutions:
  _ENV: dev
  _PROJECT_ID: epic-dev-55ae9
  _SERVICE_NAME: epic-dev-be
  _REGION: europe-west1
  _REPO: epic-dev-be
  _SERVICE_ACCOUNT: 715553450089-compute@developer.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/articulate-area-464808-q4/secrets/SLACK_WEBHOOK_URL/versions/latest
      env: SLACK_WEBHOOK_URL
    - versionName: projects/articulate-area-464808-q4/secrets/SLACK_GITHUB_TOKEN/versions/latest
      env: SLACK_GITHUB_TOKEN
    - versionName: projects/articulate-area-464808-q4/secrets/SLACK_WEBHOOK_URL_FAILURE/versions/latest
      env: SLACK_WEBHOOK_URL_FAILURE

steps:
  - id: "Build"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-south1-docker.pkg.dev/articulate-area-464808-q4/slack-notify/sample-app', '.']

  - id: "Push"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-south1-docker.pkg.dev/articulate-area-464808-q4/slack-notify/sample-app']

  - name: "ubuntu"
    id: Notify
    entrypoint: "bash"
    waitFor: ["Build", "Push"]
    secretEnv:
      ["SLACK_GITHUB_TOKEN", "SLACK_WEBHOOK_URL", "SLACK_WEBHOOK_URL_FAILURE"]
    args:
      - '-c'
      - |
        echo "🔍 Setting up..."
        echo "📦 Installing curl jq..."
        apt-get update && apt-get install -y curl jq git

        git fetch --unshallow || true

        COMMIT_SHA=$(git rev-parse HEAD)

        PARENT_COMMITS=$(git rev-list --parents -n 1 $$COMMIT_SHA)
        BEFORE_SHA=$(echo $$PARENT_COMMITS | cut -d' ' -f2)

        echo "AFTER_SHA: $$COMMIT_SHA"
        echo "BEFORE_SHA: $$BEFORE_SHA"

        git fetch --unshallow 2>/dev/null || git fetch --depth=2

        AFTER_SHA=$(git rev-parse HEAD)

        PARENT_COMMITS=$(git rev-list --parents -n 1 $$AFTER_SHA)
        BEFORE_SHA=$(echo $$PARENT_COMMITS | cut -d' ' -f2)

        echo "AFTER_SHA: $$AFTER_SHA"
        echo "BEFORE_SHA: $$BEFORE_SHA"

        echo "Fetching commit info..."
        COMMIT_API="https://api.github.com/repos/sanadivya/slack-notify-demo/commits/$$COMMIT_SHA"
        COMMIT_DATA=$(curl -s -H "Authorization: token $$SLACK_GITHUB_TOKEN" "$$COMMIT_API")
        COMMIT_MESSAGE=$(echo "$$COMMIT_DATA" | jq -r '.commit.message')
        COMMIT_AUTHOR=$(echo "$$COMMIT_DATA" | jq -r '.commit.author.name')

        set -x

        echo "📣 Sending slack notification..."
        echo "🔍 Detecting merged PR for commit: $$COMMIT_SHA"

        PR_DATA=$(curl -s -H "Authorization: token $$SLACK_GITHUB_TOKEN" \
            "https://api.github.com/search/issues?q=sha:$$COMMIT_SHA+repo:sanadivya/slack-notify-demo+is:pr")

        PR_URL=$(echo "$$PR_DATA" | jq -r '.items[0].pull_request.url')
        LATEST_PR_DATA=$(curl -s -H "Authorization: token $$SLACK_GITHUB_TOKEN" "$$PR_URL")

        PR_TITLE=$(echo "$$PR_DATA" | jq -r '.title')
        PR_NUMBER=$(echo "$$PR_DATA" | jq -r '.number')
        PR_BODY=$(echo "$$PR_DATA" | jq -r '.body')
        PR_AUTHOR=$(echo "$$PR_DATA" | jq -r '.user.login')

        echo "Deployment Details"
        echo "Commit SHA: $$COMMIT_SHA"
        echo "PR Title: $$PR_TITLE"
        echo "PR Number: #$$PR_NUMBER"
        echo "PR Description:"
        echo "$$PR_BODY"
        echo "PR Author: $$PR_AUTHOR"