name: Commitlint

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      # Checkout PR code safely (does NOT expose repo secrets to forked PRs)
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci --ignore-scripts

      - run: npx commitlint --from=origin/dev