name: Commitlint

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install --ignore-scripts

      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: ./commitlint.config.ts
          failOnWarnings: false
          failOnErrors: true
          helpURL: https://github.com/conventional-changelog/commitlint/#what-is-commitlint
          token: ${{ secrets.GITHUB_TOKEN }}
          commitDepth: 20
